import java.util.Scanner;

public class ExceptionHandlingExample {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);

        try {
            int size = input.nextInt();

            int[] array = new int[size];

            for (int i = 0; i < size; i++) {
                array[i] = input.nextInt();
            }

            int result = array[0] / array[1]; 
            System.out.println(array[3]);
            System.out.println("Result: " + result);

        } 
        catch (ArithmeticException e) {
            System.out.println("java.lang.ArithmeticException: " + e.getMessage());
        } 
        catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("java.lang.ArrayIndexOutOfBoundsException: " + e.getMessage());
        } 
        finally {
            System.out.println("I am always executed");
        }

        input.close();
    }
}
